name = "cf-panel"
main = "cloudflare-worker-complete.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cf-panel-db"
database_id = "2e4eb4d5-195b-4d86-8429-c33e80d9eef4"

[triggers]
crons = ["*/5 * * * *"]
